name: Build and Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: koenigwx
          password: ${{ secrets.TOKEN_GITHUB }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Docker repository names must be lowercase
          tags: ghcr.io/koenigwx/hdhomeruntuner:${{ github.sha }}
